### ISSUE TITLE
Keyboard shortcuts display is slightly crowded on Safari

### ISSUE THREAD

**Issue by aryairani** [unisonweb/codebase-ui#102]
![image](https://user-images.githubusercontent.com/538571/118689326-db972e80-b7d4-11eb-930c-a27fb88d9242.png)

**Comment by aryairani** [comment]
Here's what it looks like in Chrome, which is much lovelier:

![image](https://user-images.githubusercontent.com/538571/118847664-faacc380-b89b-11eb-9951-57116295bc27.png)

**Comment by hojberg** [comment]
Yeah thats not ideal hah, should be simple to fix. Might be lack of support for flex box gap

**Comment by hojberg** [comment]
Oh interesting https://css-tricks.com/safari-14-1-adds-support-for-flexbox-gaps/ - it was added and then 14.1 was pulled 🤔
