### ISSUE TITLE
On firefox, bringing up the finder using / works, but then also inputs a / into the text box

### ISSUE THREAD

**Issue by atacratic** [unisonweb/codebase-ui#136]
Guessing this is firefox only?  I'm on 89.0 for Ubuntu.

**Comment by pchiusano** [comment]
Workaround is to use the ctrl+k shortcut, which works reliably on Firefox for me.

**Comment by hojberg** [comment]
I think the `/` that is put into the field has been fixed now—ctrl+k has issues with the address bar I found.

@atacratic can you verify this works on your setup on https://share.unison-lang.org

**Comment by pchiusano** [comment]
It's cmd+k that has issues with the address bar. Ctrl+k works. 😀

**Comment by hojberg** [comment]
@pchiusano gotcha 👍

**Comment by atacratic** [comment]
> I think the / that is put into the field has been fixed now

Yup, that works! :-)
