### ISSUE TITLE
mouse pointer icon gives the (false but undesirable) impression of dead zones in the finder results

### ISSUE THREAD

**Issue by atacratic** [unisonweb/codebase-ui#139]
I move my mouse pointer around the finder results, and it flips between a little hand (that tells me it's something I can click to go somewhere) and an arrow (which suggests I needn't bother).

Actually everywhere is clickable, which is good.

But having the zones that show the arrow are distracting.

Those zones seem to be name of the definition, and any accompanying 'in base' (or wherever) note.

This is firefox 89.0 on ubuntu.

Ubuntu doesn't seem to want to include the mouse pointer in screenshots.   I've shaded the areas below in one of the results, that have the arrow.  

![image](https://user-images.githubusercontent.com/21991324/120904524-a0a25100-c644-11eb-9484-22bebe1dc767.png)

**Comment by hojberg** [comment]
Nice catch - should be a quick fix.
