### ISSUE TITLE
scrolling down behaves weirdly

### ISSUE THREAD

**Issue by atacratic** [unisonweb/codebase-ui#141]
When scrolling down through definitions in the main codebase UI pane using the down arrow (or j), the pane scrolls too soon.

Scroll up through the definitions, initially the pane stays still, until you get to the top term on the screen being highlighted.  Only then does the pane scroll (so a new definition appearing at the top, and some disappearing off the bottom).  That's good and what I feel used to.

But scrolling down, that first phase is absent: it's immediately scrolling the pane (pulling in new definitions at the bottom, scrolling some off the top), even with the highlighted term still the top one on the screen.  Feels surprising.

Firefox 89.0 on ubuntu.

**Comment by hojberg** [comment]
Yeah the automatic scrolling behavior isn't great; need to re-asses my approach.

**Comment by hojberg** [comment]
This has sense changed to open new items at the top making the scrolling behavior a lot better.
