### ISSUE TITLE
flicker when I hold down semicolon in finder (with some results showing)

### ISSUE THREAD

**Issue by atacratic** [unisonweb/codebase-ui#142]
I open finder, type something to get some results showing, and try and work out how to use the 'semicolon plus number' selection system.  After one false start (lifting the semicolon key too soon) I realize I probably need to hold down the semicolon key as if it were a key like shift.  

I try holding down semicolon and I see all the semicolon keys in the finder UI change color to encourage me (great, nice touch!)

But after a couple of seconds holding it down, the color of those semicolons starts to flicker very fast in an unsightly way.

Firefox 89.0 on ubuntu.

**Comment by atacratic** [comment]
By the way, part of why I had a false start is that the help text is a bit misleading: it says `; then 1-9`, and I interpreted the 'then' as meaning 'type semicolon (and lift the key) then type a number'.  Maybe there's some way to make this clearer?  `ctrl k` is just shown with juxtaposition.  

![Screenshot from 2021-06-05 21-46-39](https://user-images.githubusercontent.com/21991324/120905070-9170d280-c647-11eb-9427-15bc473e9c38.png)

**Comment by hojberg** [comment]
>  and I interpreted the 'then' as meaning 'type semicolon (and lift the key) then type a number'.

That is the correct interpretation. The color change is meant to indicate to started the sequence and can now press the next part of the sequence, if it isn't finished in time the sequence aborts automatically.

It sounds like this is either broken or too quick to abort.
