### ISSUE TITLE
Unison Share: Download project instruction

### ISSUE THREAD

**Issue by hojberg** [unisonweb/codebase-ui#145]
Unison Share should give instructions on how a project can be downloaded and used in `ucm`.

## Design

Users can select and copy from this input field, the `.>` will not be selectable. The button copies in the same fashion.
The question mark gives a short description of `ucm`.

<img width="412" alt="download-modal-light" src="https://user-images.githubusercontent.com/2371/124292908-14d8f300-db24-11eb-9d55-9b6fa6f68b72.png">

**Comment by hojberg** [comment]
To do this proper we kinda need a project homepage 🤔

**Comment by pchiusano** [comment]
@stew I think is working on the backend change to support this. The idea is we'll have a github repo with the Unison codebase that Unison Share is based on, and people can just pull from subpaths of this repo directly. 

Initially, the URLs will be the existing ugly git urls, but later we could support nicer urls.

**Comment by pchiusano** [comment]
@stew do we have a ticket tracking the work you're doing on this?

**Comment by hojberg** [comment]
This is out in the PR, but we have some concerns around the way versions (or lack there of) are communicating and holding back the merge until we can figure this out.
