### ISSUE TITLE
Icons are scaled weirdly when there's less space for the full name of a definition in the sidebar

### ISSUE THREAD

**Issue by hojberg** [unisonweb/codebase-ui#147]
See screenshot for an example.

<img width="241" alt="Screen Shot 2021-06-08 at 14 20 06" src="https://user-images.githubusercontent.com/2371/121258317-c023be80-c87c-11eb-8689-efee14e38626.png">

Perhaps we should truncate the text better and allow a hover to show the full name (it'd be nice if a hover showed signatures too).

**Comment by hojberg** [comment]
related: https://github.com/unisonweb/codebase-ui/issues/133

**Comment by hojberg** [comment]
Design update: 

Menu items should shrink such that first the definition category qualifier is removed then the text is truncated (fully visible in tooltip on hover). The icon should never scale down.

<img width="262" alt="truncating menu items" src="https://user-images.githubusercontent.com/2371/125012487-4b3cd380-e038-11eb-97f0-964514663b66.png">

**Comment by philderbeast** [comment]
The same thing can happen with tests:

![Screen Shot 2021-07-11 at 4 33 33 PM](https://user-images.githubusercontent.com/633283/125209296-d64ee100-e265-11eb-948a-315ff93258e5.png)
