### ISSUE TITLE
Is ucm now unison?

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/codebase-ui#165]
I built [unisonweb/unison](https://github.com/unisonweb/unison) from source but had previously installed `release/M1d` so have both `ucm` and `unison` installed.

```bash
> which unison
/Users/pdejoux/.local/bin/unison
> unison --version
unison version: latest-50-g3c8534d19

> which ucm
/usr/local/bin/ucm
> ucm --version
ucm version: release/M1d
```

I was able to follow the readme instructions to bring up the `codebase-ui` but with this change:

```diff
- ucm headless
+ unison headless
```

```bash
> unison headless

  I've started the codebase API server at
  http://127.0.0.1:59431/exnqfVFWAW9MPfb4OuzYGz30w61AQadB/api


  The Unison Codebase UI is running at
  http://127.0.0.1:59431/exnqfVFWAW9MPfb4OuzYGz30w61AQadB/ui


  Running the codebase manager headless with 1 cpu.
```

```bash
codebase-ui> API_URL="http://127.0.0.1:59431/exnqfVFWAW9MPfb4OuzYGz30w61AQadB/api" npm start
```

If I navigate a web browser to `http://127.0.0.1:59431/exnqfVFWAW9MPfb4OuzYGz30w61AQadB/ui` I see the message:
> No codebase UI configured. Set the UCM_WEB_UI environment variable to the directory where the UI is installed.

Could the readme also mention how to bring up the `codebase-ui` by setting `UCM_WEB_UI`?

**Comment by rlmark** [comment]
Hi @philderbeast, just teasing out some of the details in the ticket. Are you wanting to work on the codebase-ui specifically (i.e. make changes in the Elm front-end project against a locally running unison codebase instance) or is it your goal to write Unison code and have access to a local running instance of the codebase-ui when building from source with `stack exec unison`? If the latter is the case, you can run the `dev-ui-install.sh` script https://github.com/unisonweb/unison/blob/trunk/dev-ui-install.sh which will download the latest codebase-ui release and allow it to be built when you start your codebase with `stack exec unison`.

**Comment by philderbeast** [comment]
Hi @rlmark. Sorry for putting two items on the one ticket.

I'm up and running with the `codebase-ui` following the instructions in the readme of this repo.

If I build `unison` from source then is `ucm` named `unison`? I ran `stack install unison-parser-typechecker:unison`.

I had run the `dev-ui-install.sh` script but as the [developer.markdown](https://github.com/unisonweb/unison/blob/trunk/development.markdown) didn't say what to do with it, I ended up cloning this `codebase-ui` repo and following its readme.

I intend to write some unison.

**Comment by rlmark** [comment]
No worries @philderbeast. I've started a PR to update the readme in the unisonweb/unison repo with details on how to run a local codebase ui instance when building from source which will likely close out this ticket. You shouldn't have to run the codebase-ui with `npm start` in order to write Unison 😁 . To answer your original question, if you build unison from source, your executable is typically named unison (that's what the instructions call it, but you could technically call it something else).
