### ISSUE TITLE
Unison Share's links with path not found

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/codebase-ui#166]
If I'm browsing Unison Share at https://share.unison-lang.org the link to https://unison-lang.org works fine but those with a path segment, like https://unison-lang.org/docs, do not. I get a 404. If I manually change the URL scheme from https to http then they resolve.

https://github.com/unisonweb/codebase-ui/blob/5582a2726b6858e3d45e1b3bb53a4739a289f508/src/App.elm#L312-L315

**Comment by hojberg** [comment]
Fixed links to go to unisonweb.org.
