### ISSUE TITLE
Missing line breaks in @signatures{x, y, z}

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/codebase-ui#173]
If a `@signature{x, y, z}` block has multiple terms being shown, it looks like they are shown without linebreaks?

https://share.unison-lang.org/latest/terms/@m8f0e2vgpbkse357h6r7f0ejf8v2gem65adfek2plnlugj13cbjjufolulgme7pjrhopjeqktpk8mnn651tk38qq3o3o9tukc64k4do

Confirmed that `display` command renders this as expected, and the `Signature` constructor of the doc is giving a `[SyntaxText]`, so pretty sure it’s just a rendering tweak that’s needed.

**Comment by hojberg** [comment]
This has been fixed :D
