### ISSUE TITLE
have a way to collapse associated docs, or only partially reveal longer associated docs when a definition is opened?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/codebase-ui#187]
@hojberg What do you think?

**Comment by hojberg** [comment]
@aryairani I like the idea of a truncated doc if it is more than a specific length with a "reveal full doc" button.

There's some slightly different use cases between Unison Share and Unison Local to consider here.

**Comment by hojberg** [comment]
@aryairani

<img width="850" alt="collapsed-docs-code-on-top" src="https://user-images.githubusercontent.com/2371/135896978-72ba1a98-8573-4101-9321-789df9c033fe.png">

I think this could work.
