### ISSUE TITLE
Weird spacing on nested bulleted lists in docs?

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/codebase-ui#212]
<img width="409" alt="Screen Shot 2021-09-03 at 2 28 17 PM" src="https://user-images.githubusercontent.com/11074/132057012-f0ed608e-c9fd-4e64-8849-a7b3ffbb0130.png">

**Comment by hojberg** [comment]
I think I fixed this in a recent commit. Not on share yet I think

**Comment by hojberg** [comment]
The fix for this has been deployed to Unison Share. Closing the ticket :)
