### ISSUE TITLE
abbreviated hashes for builtin definitions

### ISSUE THREAD

**Issue by aryairani** [unisonweb/codebase-ui#213]
Hi, I just wanted to draw your attention to this to consider treating names for builtins differently from derived definitions with actual hashes.  (And maybe the result of consideration is to not treat them differently.)  But in ucm at least, we don't abbreviate the builtin references, only the derived/hash ones.

![image](https://user-images.githubusercontent.com/538571/132134616-35cfb902-31ab-4073-8c26-8f94b6fc2b5e.png)

**Comment by hojberg** [comment]
Ah good point. I wonder if its even worth showing the hash for builtins 🤔

**Comment by aryairani** [comment]
I think it is equally worth showing for builtins and user-defined stuff, but that's not really an answer.
