### ISSUE TITLE
Numbered lists in ui show "Sos" errors

### ISSUE THREAD

**Issue by rlmark** [unisonweb/codebase-ui#229]
Docs seem to have trouble rendering numbered lists. 

```
testDoc = {{

# Test Num list 

1. A
2. B 
3. C 

}}
```

is valid in the UCM, but I've attached a screenshot showing what it looks like in the UI. (Also I'm running the UI which ships with the recent m2h release, so it's possible more features have been added since then, in which case, disregard!)
 
![Screen Shot 2021-09-24 at 12 42 32 PM](https://user-images.githubusercontent.com/7613551/134731343-1379ac29-5174-43e7-ac4a-c3f62024d35a.png)

**Comment by hojberg** [comment]
That's super strange. I don't think I print out that emoji anywhere hmmm.

**Comment by pchiusano** [comment]
Pretty sure that's a bug in the backend - from a missing pattern match.

Surprised we haven't noticed it before, but it should be a quick fix in `Unison.Server.Doc`.

**Comment by rlmark** [comment]
Oh weird! I tried displaying the doc in the ucm and it went fine! I'll close this!
