### ISSUE TITLE
Numbered lists rendering should use `.` or `)` but not both

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/codebase-ui#271]
<img width="158" alt="Screen Shot 2021-11-09 at 12 18 46 PM" src="https://user-images.githubusercontent.com/11074/140981837-6cc1b128-963b-431b-af2f-e956d0598a11.png">

I vote for just the `.`, no paren.

**Comment by hojberg** [comment]
The UI doesn't insert these AFAIK. I think they are might be part of the source doc. cc @rlmark

**Comment by hojberg** [comment]
This was happening in the source document.
