### ISSUE TITLE
Bug: Unison Share UI doesn't render rich documentation

### ISSUE THREAD

**Issue by autodidaddict** [unisonweb/codebase-ui#306]
As shown in the following screenshot, when I go through the base types (e.g. Map), it doesn't show the documentation for the type when I click on the type, and when I go find the `doc` element, it just renders the raw data and doesn't give me the experience that `docs .base.Map` does from inside `ucm`

<img width="800" alt="Screen Shot 2022-01-23 at 10 43 15 AM" src="https://user-images.githubusercontent.com/13748641/150686500-e3601ded-d38a-4f56-b1fe-1462162f5683.png">

Neither the website nor `ucm` pay any heed to the markdown header indicators (e.g. the `## Constructing maps` line), but at least ucm follows the include links and gives me a single unified document.

**Comment by aryairani** [comment]
We could either add support in codebase-ui for `Doc.Deprecated`, or update Map.doc to not be `Doc.Deprecated`. Maybe a function `Doc.Deprecated -> Doc` that gets called before evaluating the `Doc` for rendering?

**Comment by hojberg** [comment]
@autodidaddict thanks for reporting. This was a deliberate decision, to not support the old version of docs, but we certainly need to—as Arya suggests—migrate the docs of base or have a function called when constructing the JSON response.

**Comment by runarorama** [comment]
It's probably best to just rewrite them

**Comment by hojberg** [comment]
Closing this. We've done a lot of work to rewrite docs in base.
