### ISSUE TITLE
Some finder searches fails in showing a namespace

### ISSUE THREAD

**Issue by hojberg** [unisonweb/codebase-ui#64]
For some reason, `examples.elems` and `input.lower` in this screenshot show without a namespace. They most certainly have one.

<img width="839" alt="Screen Shot 2021-04-28 at 15 32 53" src="https://user-images.githubusercontent.com/2371/116465118-cca70700-a83a-11eb-9e37-843121cdcda8.png">

**Comment by hojberg** [comment]
It appears that the reason for this is that the bestName and the FQN have no overlap. In other words, there are multiple names for these terms and the best name is based on a different FQN than the one matching the search query.

**Comment by runarorama** [comment]
Yeah, it's not a safe assumption that the suffixified "best" name is going to be a suffix of the found name. It's possible that we could work around this by not returning the "best" name, but instead return the shortest unambiguous suffix of the found name.

**Comment by pchiusano** [comment]
> It's possible that we could work around this by not returning the "best" name, but instead return the shortest unambiguous suffix of the found name.

This seems like the right behavior - basically, for each search result you have its FQN and its shortest unique suffix. It seems like you could do the search on the FQNs, then build the corresponding unique suffix for each FQN just before returning results.

To convert a FQN to its unique suffix - take a suffixified `Names`. And use `Name.suffixes` to iterate over the suffixes of a name. Look up each one and find the shortest that returns the same results as the original FQN.

**Comment by hojberg** [comment]
Going to close this, its tracked entirely here https://github.com/unisonweb/unison/issues/1923
