### ISSUE TITLE
Support named urls and RelativeTo namespaces

### ISSUE THREAD

**Issue by hojberg** [unisonweb/codebase-ui#78]
We want to support URL schemes like so:

```
/[latest|:namespace-hash]/[namespaces|types|terms]/[:definition-name|:definition-hash]
```

When we have a namespace hash (either for the top level codebase or for a sub namespace), any term or type name in the url will be relative to that and does not need to be identified by hash unless that definition sits outside of the enclosing `RelativeTo` namespace.

_Aside: Unison hashes in URLs use `@` instead of `#` to conform to the URL specification._

## Relative URL example

A relative URL refers to URLs that point to the latest version of codebase or definition. It's addressing by name instead of by hash. 

Relative URLs will be turned into absolutes as soon as the page loads by exchanging `latest` for the latest hash of the codebase. **We want to encourage absolute linking over relative**, but support relative for things like a project website linking to the latest of a codebase. 

* Toplevel of a Codebase: `/latest`
* Workspace namespace: `/latest/namespaces/base/List`
* Definitions: `/latest/[types|terms]/base/List` 
* Ambiguous definitions:`/latest/[types|terms]/base/List@je2wR6`

## Absolute URL examples

Absolute URLs link directly to the version of a codebase or definition by using hashes.

* Workspace namespace: `/@785shikvuihsdfd`
* Definitions:`/@785shikvuihsdfd/[types|terms]/base/List`
* Ambiguous definitions:`/@785shikvuihsdfd/[types|terms]/Nonempty/map@dkqA42`
* Definitions outside of workspace:`/@785shikvuihsdfd/[types|terms]/@jf615sgdkvuihskrt`
* Definitions outside of workspace:`/latest/[types|terms]/@jf615sgdkvuihskrt`—**Only supported URL currently**

#### Absolute URL notes

* `@785shikvuihsdfd` refers to a specific namespace hash in the codebase. In this case `base.List` , but could also be the hash of the top level codebase. `@jf615sgdkvuihskrt` refers to a definition outside of `base.List`
* With this it is **not** possible to relatively link to a definition in where the workspace is also set relatively. The user would instead link with an absolute workspace: `/@785shikvuihsdfd/[types|terms]/Nonempty`

## Implications

* This feature requires a way to exchange a namespace name or "latest" to a hash.
* The frontend will make a request to the server when it is first initiated with a relative URL to exchange it for a hash and rewrite the URL.
* This feature allows nice URLs on Unison Share, allowing users to see what they are being linked before clicking through

---

Additional reading: https://github.com/unisonweb/codebase-ui/blob/main/docs/design/relative-to-changing-fetching-by-name-vs-hash-indexing-and-urls.md

**Comment by philderbeast** [comment]
Having a stable URL would be great for reviewing rendered docs while editing them. At the moment, if I'm looking at DirectProblem.doc in the codebase-ui, update it and then refresh the page, I get something that doesn't render and to review my updated changes rendered, I need to navigate the tree to select the item that was previously selected.

```
#jth3k84373fd0b53m2lnigvhkpps0ks3ci7b4iivv87s1nf6mbjln6hdnl4kt2sb8hqkuksagbvo8tkn3ur983s9j7g0p93bcurtng8
Unable to load definition: Term #jth3k84373fd0b53m2lnigvhkpps0ks3ci7b4iivv87s1nf6mbjln6hdnl4kt2sb8hqkuksagbvo8tkn3ur983s9j7g0p93bcurtng8 — please try again.
```

**Comment by hojberg** [comment]
We definitely intend to be able to render old definitions, which is the whole point of having the hash in the url, but its also an interesting point that the hash in the url is perhaps mostly (exclusively?) useful on Unison Share 🤔 

Also interesting to consider what this would mean in the Electron world for the local app where there are no URL.

**Comment by hojberg** [comment]
Removed the backend requirement as this can be done with the `/list` API (though we'd likely eventually want to move this to a `/namespace` API that gives more detail, like a readme).

**Comment by hojberg** [comment]
This is finally fixed by https://github.com/unisonweb/codebase-ui/pull/189
